#!/usr/bin/env bash
set -euo pipefail

hash=$(
  git log -n 500 --pretty=format:'%h %s' --no-merges |
  fzf \
    --no-sort \
    --preview='git show --stat {1}' \
    --header='Select a commit to fixup' |
  cut -c -7
)

[ -n "$hash" ] && git commit "$@" --fixup "$hash"
